customer/urls.py
from django.urls import path
from . import views


urlpatterns = [    
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('resendactivationemail/',views.ResendActivationEmail.as_view(),name='resendactivationemail'),   

    # path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('activate/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('resetpassword/',views.ResetPassword.as_view(),name='resetpassword'),
    path('createnewpassword/<uidb64>/<token>/',views.CreateNewPassword.as_view(),name="createnewpassword"),  

    path('profile/',views.Profile.as_view(),name='profile'),
    # path('profiledetails/',views.ProfileDetails.as_view(),name='profiledetails'),
    path('changepassword/',views.ChangePassword.as_view(),name='changepassword'),
    #path('myaddresses/',views.AllAddress,name='myaddresses'),
    path('address/',views.Address.as_view(),name='address'),
    path('address/<int:id>',views.Address.as_view(),name='address'),
    #path('deleteaddress/<int:id>',views.DeleteAddress,name='deleteaddress'),
    #path('setasdefault/<int:id>',views.SetAddressAsDefault,name='setasdefault'),

    path('ordersuccess/',views.OrderPlaced,name='ordersuccess'),
    path('orderfailed/',views.OrderFailed,name='orderfailed'),
    path('ordersuccessful/<str:orderid>',views.OrderSuccess,name='ordersuccessful'),
    path('printinvoice/<str:orderid>/',views.PrintInvoice,name='printinvoice'),
    path('getinvoice/<str:orderid>/',views.GetInvoice,name='getinvoice'),

    path('orders/',views.Orders,name='orders'),
    # path('tracking/<int:oid>/',views.UpdateTrackingInfo,name='tracking'),
    # path('updatestatus/<int:oid>/',views.UpdateOrderStatus,name='updatestatus'),

    path('cancelorder/<int:oid>/',views.CancelOrder,name='cancelorder'),
    path('returnproduct/<int:orderitemid>/',views.ReturnProduct,name='returnproduct'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('',views.index,name='home'),  
    path('cartsummary/',views.cartsummary,name='cartsummary'),
    path('makepayment/',views.MakePayment,name='makepayment'),
    path('category/<str:cid>/',views.FilterByCategory,name='category'),
    path('allproducts/',views.AllProducts,name='allproducts'),
    path('search/',views.SearchResults,name='search'),

    path('filterproduct',views.FilterProducts,name='filterproduct'),
    path('clearfilter/',views.ClearFilter,name='clearfilter'),
    path('clearfilter/<str:category>/',views.ClearFilter,name='clearfilter'),
    path('pinproducts/',views.FilterByPin,name="pinproducts"), 

    path('aboutus/',views.AboutUs,name='aboutus'),
    path('affiliate/',views.Affiliate,name='affiliate'),
    path('cancellations/',views.Cancellations,name='cancellations'),
    path('careers/',views.Careers,name='careers'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('faqs/',views.FAQ,name='faqs'),
    path('help/',views.Help,name='help'),
    path('payments/',views.Payments,name='payments'),
    path('payouts/',views.Payouts,name='payouts'),
    path('press/',views.Press,name='press'),
    path('howtocare/', views.Howtocare,name='howtocare'),
    path('privacypolicy/',views.PrivacyPolicy,name='privacypolicy'),
    path('refundpolicy/',views.RefundPolicy,name='refundpolicy'),
    path('returnpolicy/',views.ReturnPolicy,name='returnpolicy'),
    path('shippingpolicy/',views.ShippingPolicy,name='shippingpolicy'),
    path('terms/',views.TermsAndConditions,name='terms'),
    path('vendorfaqs/',views.VendorFAQ,name='vendorfaqs'),
    path('vendorassistance/',views.VendorHelp,name='vendorassistance'),
    path('requestproduct/',views.RequestProduct,name='requestproduct'),   
    #path('404/',views.PageNotFound,name='404'),
    #path('404/',views.ServerUnavailable,name='503'),
    path("test-session/", views.test_session)

    
]

podhewale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path(settings.SECRET_ADMIN_URL +'/admin/', admin.site.urls),
	    path('',include('home.urls')),
	    path('customer/',include('customer.urls')),
	    path('vendor/',include('vendor.urls',namespace="vendor")),
	    path('product/',include('product.urls')),
	] 

if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class RequestedProducts(models.Model):
    emailAddress = models.CharField(max_length=100,null=True,blank=True)
    fullName = models.CharField(max_length=100,null=True,blank=True)
    requestDescription = models.CharField(max_length=1000,null=True,blank=True)
    dateAdded = models.DateTimeField(auto_now_add=True)

home/views/baseview.py
from unicodedata import category
from django.shortcuts import redirect, render
from django.db.models.query_utils import Q
from home.models import RequestedProducts
from product.models import Category, Product
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



# def index(request):
#     pin = request.session.get('pincode')
#     if pin is None or pin == '':
#         products = Product.objects.filter(is_live=True,category__categoryName='Plants')
#     else:
#         products = Product.objects.filter(is_live=True,addedBy__address__pinCode = pin)
#     categories = Category.objects.all()
#     return render(request,'home/index.html',{"products":products,"categories":categories})

def index(request):
    products = Product.objects.filter(is_live=True)
    categories = Category.objects.all()    
    cart = request.session.get("cart")    
    return render(request,'home/index.html',{"products":products,"categories":categories})


def FilterByCategory(request,cid):
    category = Category.objects.get(categoryName=cid)
    categories = Category.objects.all()
    # pin = request.session.get('pincode')
    # if pin is None or pin == '':
    products = Product.objects.filter(category=category,is_live=True)
    # else:
    #     products = Product.objects.filter(category=category,is_live=True,addedBy__address__pinCode = pin)
    paginator = Paginator(products, 5)  # Show 25 contacts per page.    

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request,'home/categories.html',{"category":category,"page_obj":page_obj,"categories":categories,"categoryid":cid})

def AllProducts(request):    
    products = Product.objects.filter(is_live=True)
    paginator = Paginator(products, 5)  # Show 25 contacts per page.
    categories = Category.objects.all()

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    #return render(request, "list.html", {"page_obj": page_obj})
    return render(request,'home/categories.html',{"page_obj":page_obj,"categories":categories})


def SearchResults(request):
    query = request.GET['search']
    pin = request.session.get('pincode')
    if pin is None or pin == '':
        products = Product.objects.filter(Q(tagCloud__icontains=query) | Q(productName__icontains=query)| Q(productDescription__icontains=query))
    else:
        products = Product.objects.filter(Q(tagCloud__icontains=query) | Q(productName__icontains=query)| Q(productDescription__icontains=query),addedBy__address__pinCode = pin)  

    paginator = Paginator(products, 5)  # Show 25 contacts per page.    

    page_number = request.GET.get("page")  
    page_obj = paginator.get_page(page_number)
    return render(request,'home/searchresults.html',{"products":products,"page_obj":page_obj,"query":query})
    #return render(request, "home/searchresults.html",{"products":products,"query":query})



def FilterProducts(request):
    
    minprice = request.GET["minprice"]
    maxprice = request.GET["maxprice"]
    planttype = request.GET["planttype"]
    productsize = request.GET["productsize"]
    category = request.GET['category']  
    search=request.GET['query']
    sortby = request.GET['sorting']

    





    if minprice == "":
        minprice = 0    
    if maxprice =="":
        maxprice=99999

    if category != "":
        selcategory = Category.objects.filter(categoryName=category).first()
        products = Product.objects.filter(productSalePrice__gte=minprice, productSalePrice__lte=maxprice, category=selcategory)
    elif search != "":
        products = Product.objects.filter(Q(tagcloud__contains=search) | Q(productName__contains=search)| Q(productDescription__contains=search))
        products = products.filter(productSalePrice__gte=minprice, productSalePrice__lte=maxprice)
    else:
        products = Product.objects.filter(productSalePrice__gte=minprice, productSalePrice__lte=maxprice) 

    
    # if pincode != "":
    #     products = products.filter(addedby__User__pincode = pincode)
    
    if planttype !="":
        products = products.filter(tagCloud__contains=planttype)
    
    if productsize != "":
        products = products.filter(size=productsize)

    if sortby == "sortascending":
        products=products.order_by('productSalePrice')
    elif sortby == "sortdescending":
        products=products.order_by('-productSalePrice')
    elif sortby == "newfirst":
        products=products.order_by('-addedOn')
    elif sortby == "oldfirst":
        products=products.order_by('addedOn')   
    elif sortby == "rating":
        products=products.order_by('-productrating__rating')

    pin = request.session.get('pincode')
    if not pin is None and pin != '':
        products=products.filter(addedBy__address__pinCode = pin)

    args = {}
    args['products'] = products
    args['minprice'] = minprice
    args['maxprice'] = maxprice
    # args['pincode'] = pincode
    args['planttype'] = planttype
    args['productsize'] = productsize
    args['categoryid'] = category
    args['query'] = search
    args['sortby'] = sortby

    categories = Category.objects.all()
    args['categories'] = categories


    return render(request,'home/categories.html',args)
    

def ClearFilter(request,category=''):    
    if category == '':
        return redirect('home')
    else:
        url = "{}/{}".format("/category",category)
        return redirect(url)


def FilterByPin(request):
    pin = request.GET["filterpincode"]    
    # products = Product.objects.filter(addedBy__address__pinCode = pin)
    # categories = Category.objects.all()
    request.session["pincode"] = pin
    return redirect("home")




def AboutUs(request):
    categories = Category.objects.all()
    return render(request,"home/aboutus.html",{"categories":categories})

def Careers(request):
    return render(request,"home/careers.html")

def ContactUs(request):
    return render(request,"home/contactus.html")

def FAQ(request):
    return render(request,"home/faqs.html")

def Help(request):
    return render(request,"home/help.html")

def Payments(request):
    return render(request,"home/payments.html")

def Press(request):
    return render(request,"home/press.html")

def PrivacyPolicy(request):
    return render(request,"home/privacypolicy.html")

def RefundPolicy(request):
    return render(request,"home/refundpolicy.html")

def ReturnPolicy(request):
    return render(request,"home/returnpolicy.html")

def ShippingPolicy(request):
    return render(request,"home/shippingpolicy.html")

def TermsAndConditions(request):
    return render(request,"home/termsandconditions.html")

def Cancellations(request):
    return render(request,"home/cancellations.html")


def VendorFAQ(request):
    return render(request,"home/vendorfaqs.html")

def VendorHelp(request):
    return render(request,"home/vendorhelp.html")

def Payouts(request):
    return render(request,"home/payouts.html")

def Affiliate(request):
    return render(request,"home/affiliate.html")

def Howtocare(request):
    return render(request,"home/howtocare.html")


def RequestProduct(request): 

    if request.POST:
        email = request.POST["email"]
        fname = request.POST["fullname"]
        desc= request.POST["requesttext"]
        reqorder = RequestedProducts.objects.create(emailAddress=email,fullName=fname,requestDescription= desc)  
        reqorder.save()
        messages.success(request,"Request Submitted Successfully! We will get back to you soon.")        
    return render(request,"home/requestproduct.html")

def PageNotFound(request):
    return render(request,"404.html")

def ServerUnavailable(request):
    return render(request,"503.html")

from django.http import HttpResponse
    
def test_session(request):
    request.session["test"] = "hello"
    request.session.save()
    return HttpResponse("Session test done!")

home/views/mainview.py
from email.headerregistry import Address
from django.conf import settings
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction
import razorpay
from customer.models import RazorOrder, UserAddress

from product.models import Product




@login_required
def cartsummary(request):
    if request.user.is_vendor:
        return redirect("/")
    #address = UserAddress.objects.filter(user=request.user.Customer, is_primary=True).first()  
    #if address is None or address.address1  == "" or address.address1 is None:
    #   messages.info(request,"We need your default address details before you can place an order!")    
    #  return redirect('/customer/myaddresses')
    if request.user.fullName is None:
        messages.info(request,"Please complete your profile details before placing an order!")
        return redirect('/customer/profile')    
    cart = request.session.get("cart")
    if cart is None:    
        cart={}
        request.session["cart"] = cart  
    cart = request.session.get("cart")
    products = Product.objects.filter(id__in=cart.keys()) 
    # addresses = UserAddress.objects.filter(user=request.user.Customer, is_active=True)   
    address = ""
    try:
        address = UserAddress.objects.get(user=request.user.Customer)
    except:
        messages.error(request,"Please add an address to continue!")
        return redirect("/customer/address")
    request.session["addressid"] = address.id
    addressid = request.session.get("addressid")
    couponcode = ''
    couponcode = request.session.get("couponcode")
    if request.POST:
        addressid=int(request.POST['group1'])
        request.session["addressid"] = addressid
        return render(request,"home/cartsummary.html",{"products":products,"addressid":addressid,"couponcode":couponcode,"address":address})
    elif not addressid is None:
        return render(request,"home/cartsummary.html",{"products":products,"addressid":int(addressid),"couponcode":couponcode,"address":address})
    else:
        return render(request,"home/cartsummary.html",{"products":products,"couponcode":couponcode,"address":address})
    

def MakePayment(request):
    aid = request.session.get("addressid")
    if aid is None:
        messages.info(request,"Please select or add an address!")
        return redirect("/cartsummary")

    cart = request.session.get("cart")
    delcart = []
#    addressid = request.session.get("addressid")
#   address = UserAddress.objects.filter(id=addressid).first()
#    if not address is None:
#        addpin = address.pinCode
#        for key in cart.keys():
#            product = Product.objects.filter(id=key).first()
#            if product.addedBy.address.pinCode != addpin:
#                delcart.append(key)
#        if len(delcart) > 0:
#            for d in delcart:
#                del cart[str(d)]
#            request.session["cart"] = cart
#            messages.info(request,"Some Products may have been removed from your cart based on you selected address! Please review.")
#           return redirect('cartsummary')



    orderamt = float(request.POST["orderamt"])
    razorclient = razorpay.Client(auth=(settings.RAZORPAYID,settings.RAZORPAYKEY))
    data = {'amount':(orderamt*100),'currency':'INR'}
    razorOrder = razorclient.order.create(data)

    
    args={}
    cart = request.session.get("cart")
    products = Product.objects.filter(id__in=cart.keys())
    args['products'] = products
    args['orderid'] = razorOrder['id']
    args['username'] = request.user.fullName
    args['useremail'] = request.user.username
    args['contactno'] = request.user.contactNumber
    args['key'] = settings.RAZORPAYID
    args['coupon'] = "coupon"
    args['addressid'] = request.session.get("addressid")
    args['surl'] = "https://" + str(get_current_site(request)) +  "/customer/ordersuccess/"


    address = UserAddress.objects.filter(id=request.session.get("addressid")).first()
    args['address'] = address
    cart = request.session.get('cart')
    RazorOrder.objects.create(razorOrderId=razorOrder['id'],userId=request.user.id,cartDict=str(cart))
    return render(request,"home/makepayment.html", args)

templates/home/affiliate.html
{% extends 'design.html' %}
{% block title1 %}Affiliate{% endblock %}
{% block title2 %}Affiliate{% endblock %}

{% block content %}
<div class="m-5 p-5 text-justify">Affiliate</div>
{% endblock content %}

templates/home/footer.html
<div class="footer">
    <div class="container">
        <div class="row m-auto">
            <div class="col-6">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-6 lh-lg mt-3">
                    <b class="fs-6">Customer Care:</b><br/>
                        Phone: 9911554948<br/>
                        WhatsApp: 9911554948<br/>
                        Email:podhewale@gmail.com                        
                    </div>
                    <div class="col-12 col-md-6 col-lg-6 lh-lg mt-3">
                        <b class="fs-6">Registered Office Address:</b><br/>
                        SS Trading owned and maintain by Gagan Punia Group<br/>
                        C-1/138 gali no.6 Near Mandoli jail complex, Harsh Vihar,<br/>
                        East Delhi - 110093
                    </div>
                    
                </div>
            </div>
            <div class="col-6">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3 mt-3">
                        <a href="/">Shop</a>
                        <a href="/">Home</a>
                        <a href="{% url 'help' %}">Help</a>
                        <a href="{% url 'terms' %}">Terms/Conditions</a>
                        <a href="{% url 'refundpolicy' %}">Refund Policy</a>
                        <a href="{% url 'cancellations' %}">Cancellation Policy</a>
                        <a href="{% url 'returnpolicy' %}">Return Policy</a>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3 mt-3">
                        <a href="{% url 'aboutus' %}">About Us</a>
                        <a href="{% url 'contactus' %}">Contact Us</a>
                        <a href="{% url 'careers' %}">Careers</a>
                        <a href="{% url 'faqs' %}">FAQs</a>
                        <a href="{% url 'shippingpolicy' %}">Shipping</a>
                        <a href="{% url 'payments' %}">Payments</a>
                        <a href="{% url 'press' %}">Press</a>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3 mt-3">
                        <a href="">FaceBook</a>
                        <a href="">Instagram</a>
                        <a href="https://api.whatsapp.com/send?phone=9911554948">WhatsApp</a>
                        <a href="https://twitter.com/podhewale_com">Twitter</a>
                        <a href="">Pinterest</a>
                        <a href="">YouTube</a>
                        <a href="">Quora</a>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3 mt-3">
                        <a href="{% url 'vendor:signup' %}">Become a Seller</a>
                        <a href="{% url 'vendor:login' %}">Seller Login</a>
                        <a href="{% url 'affiliate' %}">Become an Affiliate</a>
                        <a href="{% url 'vendorfaqs' %}">Vendor FAQs</a>
                        <a href="{% url 'vendorassistance' %}">Vendor Assistance</a>
                        <a href="{% url 'payouts' %}">Payouts</a>
                                                
                    </div>
                </div>
                
            </div>

        </div>        
    </div>  

<hr>
<p class="text-center m-1">&copy;2022 Gagan Punia Group</p>
 
   {% comment %} <p class="fs-xsmall text-center">Designed & Developed by<a href="http://mashbox.in" class="text-light d-inline opacity-100"> Mashbox.in</a></p> {% endcomment %}
</div>

templates/home/help.html
{% extends 'design.html' %}

{% block content %}
<div class="m-5 p-5 text-justify">Help</div>
{% endblock content %}

templates/home/payments.html
{% extends 'design.html' %}

{% block content %}
<div>Payments</div>
We accept all types of payment. And all the payment will be done by Razorpay Gateway.
{% endblock content %}

templates/home/payouts.html
{% extends 'design.html' %}

{% block content %}
<div>Payouts</div>
{% endblock content %}

templates/home/press.html
{% extends 'design.html' %}

{% block title1 %}Press{% endblock %}
{% block title2 %}Pess{% endblock %}
{% block content %}
<div>Press Release</div>
{% endblock content %}

templates/home/privacypolicy.html
{% extends 'design.html' %}
{% block title1 %}Privacy Policy{% endblock %}
{% block title2 %}Privacy Policy{% endblock %}
{% block content %}
<div class="m-1 p-1 m-md-5 p-md-5 text-justify">
    <h4 class="my-2"><b>Privacy Policy</b></h4>
    Please review our Privacy Notice, which also governs your visit to Podhewale.com, to understand our practices.
    <h4 class="my-2"><b></b></h4> 
    The personal information / data provided to us by you during the course of usage of Podhewale.com will be used for further usage with other persons; as and when required and applicable laws and regulations.
    <h4 class="my-2"><b></b></h4> 
    If you object to your information being transferred or used, please do not use the website.
    <h4 class="my-2"><b></b></h4>
    We may update this Privacy Policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons.
    <h4 class="my-2"><b></b></h4>
    We retain your personal information only for as long as necessary to provide you with our services and as described in our Privacy Policy.
    <h4 class="my-2"><b></b></h4>
    However, we may also be required to retain this information to comply with our legal and regulatory obligations, to resolve disputes, and to enforce our agreements.
{% endblock content %}

templates/home/shippingpolicy.html
{% extends 'design.html' %}
{% block title1 %}Shipping Policy{% endblock %}
{% block title2 %}Shipping Policy{% endblock %}

{% block content %}
<div class="m-1 p-1 m-md-5 p-md-5 text-justify">

<h4 class="my-2"><b>Delivery Process</b></h4>
Product or item will be delivered within 2 - 4 business days.

<h4 class="my-2"><b></b></h4>
The Delivery must be done by the Sellers generally.

<h4 class="my-2"><b></b></h4>
We send the product to you only after checking with our experts.
<h4 class="my-2"><b></b></h4>
The Delivery may be charged any delivery fee or charge which will be independent and separate from the product cost and will be charged for each product separately independent from any specific basis or method.

<h4 class="my-2"><b>Delivery Address</b></h4>
Please ensure that the shipping address provided during checkout is accurate and complete. We are not responsible for any delays or non-delivery due to incorrect or incomplete addresses.

<h4 class="my-2"><b>Shipping Delays</b></h4>
While we strive to ensure prompt delivery of your orders, please note that shipping delays may occur due to factors beyond our control, such as weather conditions, carrier disruptions, or high order volumes.

 {% endblock content %}

templates/home/vendorhelp.html
{% extends 'design.html' %}

{% block content %}
<div class="m-5 p-5 text-justify">Seller help</div>
{% endblock content %}