customer/urls.py
from django.urls import path
from . import views


urlpatterns = [    
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('resendactivationemail/',views.ResendActivationEmail.as_view(),name='resendactivationemail'),   

    # path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('activate/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('resetpassword/',views.ResetPassword.as_view(),name='resetpassword'),
    path('createnewpassword/<uidb64>/<token>/',views.CreateNewPassword.as_view(),name="createnewpassword"),  

    path('profile/',views.Profile.as_view(),name='profile'),
    # path('profiledetails/',views.ProfileDetails.as_view(),name='profiledetails'),
    path('changepassword/',views.ChangePassword.as_view(),name='changepassword'),
    #path('myaddresses/',views.AllAddress,name='myaddresses'),
    path('address/',views.Address.as_view(),name='address'),
    path('address/<int:id>',views.Address.as_view(),name='address'),
    #path('deleteaddress/<int:id>',views.DeleteAddress,name='deleteaddress'),
    #path('setasdefault/<int:id>',views.SetAddressAsDefault,name='setasdefault'),

    path('ordersuccess/',views.OrderPlaced,name='ordersuccess'),
    path('orderfailed/',views.OrderFailed,name='orderfailed'),
    path('ordersuccessful/<str:orderid>',views.OrderSuccess,name='ordersuccessful'),
    path('printinvoice/<str:orderid>/',views.PrintInvoice,name='printinvoice'),
    path('getinvoice/<str:orderid>/',views.GetInvoice,name='getinvoice'),

    path('orders/',views.Orders,name='orders'),
    # path('tracking/<int:oid>/',views.UpdateTrackingInfo,name='tracking'),
    # path('updatestatus/<int:oid>/',views.UpdateOrderStatus,name='updatestatus'),

    path('cancelorder/<int:oid>/',views.CancelOrder,name='cancelorder'),
    path('returnproduct/<int:orderitemid>/',views.ReturnProduct,name='returnproduct'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('',views.index,name='home'),  
    path('cartsummary/',views.cartsummary,name='cartsummary'),
    path('makepayment/',views.MakePayment,name='makepayment'),
    path('category/<str:cid>/',views.FilterByCategory,name='category'),
    path('allproducts/',views.AllProducts,name='allproducts'),
    path('search/',views.SearchResults,name='search'),

    path('filterproduct',views.FilterProducts,name='filterproduct'),
    path('clearfilter/',views.ClearFilter,name='clearfilter'),
    path('clearfilter/<str:category>/',views.ClearFilter,name='clearfilter'),
    path('pinproducts/',views.FilterByPin,name="pinproducts"), 

    path('aboutus/',views.AboutUs,name='aboutus'),
    path('affiliate/',views.Affiliate,name='affiliate'),
    path('cancellations/',views.Cancellations,name='cancellations'),
    path('careers/',views.Careers,name='careers'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('faqs/',views.FAQ,name='faqs'),
    path('help/',views.Help,name='help'),
    path('payments/',views.Payments,name='payments'),
    path('payouts/',views.Payouts,name='payouts'),
    path('press/',views.Press,name='press'),
    path('howtocare/', views.Howtocare,name='howtocare'),
    path('privacypolicy/',views.PrivacyPolicy,name='privacypolicy'),
    path('refundpolicy/',views.RefundPolicy,name='refundpolicy'),
    path('returnpolicy/',views.ReturnPolicy,name='returnpolicy'),
    path('shippingpolicy/',views.ShippingPolicy,name='shippingpolicy'),
    path('terms/',views.TermsAndConditions,name='terms'),
    path('vendorfaqs/',views.VendorFAQ,name='vendorfaqs'),
    path('vendorassistance/',views.VendorHelp,name='vendorassistance'),
    path('requestproduct/',views.RequestProduct,name='requestproduct'),   
    #path('404/',views.PageNotFound,name='404'),
    #path('404/',views.ServerUnavailable,name='503'),
    path("test-session/", views.test_session)

    
]

podhewale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path(settings.SECRET_ADMIN_URL +'/admin/', admin.site.urls),
	    path('',include('home.urls')),
	    path('customer/',include('customer.urls')),
	    path('vendor/',include('vendor.urls',namespace="vendor")),
	    path('product/',include('product.urls')),
	] 

if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.db.models.deletion import CASCADE, DO_NOTHING
from django.core.validators import MaxLengthValidator, MinLengthValidator
from common.models import User

# ENUMS

STATES = (
    ("Andaman-and-Nicobar-Islands","Andaman and Nicobar Islands"),
    ("Andhra-Pradesh","Andhra Pradesh"),
    ("Arunachal-Pradesh","Arunachal Pradesh"),
    ("Assam","Assam"),
    ("Bihar","Bihar"),
    ("Chandigarh","Chandigarh"),
    ("Chhattisgarh","Chhattisgarh"),
    ("Dadra-Nagar-Haveli","Dadra Nagar Haveli"),
    ("Delhi","Delhi"),
    ("Goa","Goa"),
    ("Gujarat","Gujarat"),
    ("Haryana","Haryana"),
    ("Himachal-Pradesh","Himachal Pradesh"),
    ("Jammu-and-Kashmir","Jammu and Kashmir"),
    ("Jharkhand","Jharkhand"),
    ("Karnataka","Karnataka"),
    ("Kerala","Kerala"),
    ("Ladakh","Ladakh"),
    ("Lakshadweep","Lakshadweep"),
    ("Madhya-Pradesh","Madhya Pradesh"),
    ("Maharashtra","Maharashtra"),
    ("Manipur","Manipur"),
    ("Meghalaya","Meghalaya"),
    ("Mizoram","Mizoram"),
    ("Nagaland","Nagaland"),
    ("Odisha","Odisha"),
    ("Puducherry","Puducherry"),
    ("Punjab","Punjab"),
    ("Rajasthan","Rajasthan"),
    ("Sikkim","Sikkim"),
    ("TamilNadu","TamilNadu"),
    ("Telangana","Telangana"),
    ("Tripura","Tripura"),
    ("Uttarakhand","Uttarakhand"),
    ("Uttar-Pradesh","Uttar Pradesh"),
    ("West-Bengal","West Bengal"),
)

ORDERSTATUS = (
    ("PaymentPending","Payment Pending"),    
    ("Cancelled","Cancelled"),
    ("RefundPending","Refund Pending"),
    ("Processing","Processing"),
    ("Packed","Packed"),
    ("Shipped","Shipped"),
    ("Delivered","Delivered"),
    ("ReturnRequested","Return Requested"),
    ("RefundIssued","Refund Issued"),
)

COURIERPARTNERS = (
    ('DelhiVery','Delivery'),
    ('BlueDart','BlueDart'),
    ('DHL','DHL'),
    ('Ekart','Ekart'),
    ('DTDC','Podhewale'),
    ('Aramex','Aramex'),
    ('Ecom','Ecom'),
    ('FedEx','FedEx'),
    ('Gati','Gati'),
    ('SafeExpress','SafeExpress'),
    ('ProfessionalCouriers','ProfessionalCouriers'),

)

# ADDRESSTYPE = (
#     ('Billing Address','BillingAddress'),
#     ('Shipping Address','ShippingAddress'),    

# )


# OTPType = (
#     ("SignUp","SignUp"),
#     ("PasswordReset","PasswordReset"),
# )

# class UserOTP(models.Model):
#     user = models.OneToOneField(User,on_delete=CASCADE)
#     otp = models.CharField(max_length=6,null=True,blank=True)
#     active =models.BooleanField(default=False)
#     lastgeneratedon = models.DateTimeField(blank=True,null=True)
#     lastusedon = models.DateTimeField(blank=True,null=True)
#     usedfor = models.CharField(choices=OTPType, max_length=50)

#     class Meta:
#         verbose_name_plural = "User OTP"


class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=CASCADE,related_name="Customer")
    # otpType = models.CharField(max_length=100,choices=OTPType, default=None)
    otpNumber = models.TextField(max_length=6,default=0,blank=True)

    def __str__(self):
        return self.user.username

class UserAddress(models.Model):
    user = models.ForeignKey(Customer,on_delete=CASCADE,related_name="address")
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100,blank=True,null=True)
    city= models.CharField(max_length=100,blank=True,null=True)
    landMark = models.CharField(max_length=100,blank=True,null=True)
    state = models.CharField(max_length=100,choices=STATES,default=None)
    pinCode = models.CharField(max_length=6,validators=[MinLengthValidator(6),MaxLengthValidator(6)])
    contactNumber = models.CharField(max_length=10,validators=[MinLengthValidator(10),MaxLengthValidator(10)])
    contactPerson = models.CharField(max_length=100)
    is_primary = models.BooleanField(default=0)
    is_active = models.BooleanField(default=1)
    # address_type=models.CharField(max_length=100,choices=ADDRESSTYPE,default=None)

    def __str__(self):
        return str(self.user.user)

class Order(models.Model):
    def CustomOrderId(self):
        return "ORD" + self.orderedOn.strftime("%m%d%Y") + str(self.id)
    
    user = models.ForeignKey(User,on_delete=DO_NOTHING)    
    orderId= property(CustomOrderId)
    orderedOn = models.DateTimeField(auto_now_add=True)
    couponCode = models.CharField(max_length=100,blank=True,null=True)
    discount = models.FloatField(blank=True, null=True,default=0)
    orderTotal = models.FloatField(blank=True, null=True,default=0)
    taxOnOrder = models.FloatField(blank=True, null=True,default=0)
    orderStatus = models.CharField(max_length=100,choices=ORDERSTATUS)
    razorOrderId = models.CharField(max_length=50,blank=True,null=True)
    razorPaymentId = models.CharField(max_length=50,blank=True,null=True)
    razorSignature = models.CharField(max_length=150,blank=True,null=True)
    trackingInfo = models.CharField(max_length=30,blank=True,null=True,default='')
    trackingProvider = models.CharField(max_length=100,choices=COURIERPARTNERS,null=True,blank=True,default='')
    addressid = models.IntegerField()
    deliveryDate = models.DateField(null=True,blank=True)

    def __str__(self):
        return self.orderId

    class Meta:
        verbose_name_plural = "Orders"

class OrderItems(models.Model):
    order = models.ForeignKey(Order,on_delete=CASCADE)
    productId = models.CharField(max_length=100)
    productName = models.CharField(max_length=200)
    unitPrice = models.FloatField(default=0)
    listPrice = models.FloatField(default=0)
    paidPrice = models.FloatField(default=0)
    taxAmount = models.FloatField(default=0)
    discountAmount = models.FloatField(default=0)
    quantity = models.IntegerField(default=1)
    vendorId = models.IntegerField()
    userId = models.CharField(max_length=100, default='')    
    returnRequested = models.BooleanField(default=0)
    returnStatus = models.CharField(max_length=50,blank=True,null=True)
    appointmentDate = models.CharField(max_length=100)
    appointmentTime = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Order Items"

    def __str__(self):
        return str(self.order.orderId) + "  Product Name: " + str(self.productName) + " Quantity: " + str(self.quantity)

class RazorOrder(models.Model):
    razorOrderId = models.CharField(max_length=50,blank=True,null=True)
    userId = models.CharField(max_length=50,blank=True,null=True)
    cartDict = models.CharField(max_length=500,blank=True,null=True)
    checkoutTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.razorOrderId


class WishList(models.Model):
    user=models.ForeignKey(Customer,on_delete=CASCADE)
    productId = models.CharField(max_length=100, default=0)
    addedOn = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.addedOn

customer/views/accountview.py
from email.headerregistry import Address
from django.shortcuts import redirect, render
from django.views import View
from common.models import User
from customer.forms import AddressForm, ChangeUserPasswordForm, EditUserForm, LoginForm, ResendActivationForm, ResetPasswordForm, SetNewPasswordForm, SignupForm
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils.encoding import force_bytes, force_text, iri_to_uri

from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.db import transaction
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from customer.models import Order, UserAddress
from product.models import Product


class Profile(View):
    @method_decorator(login_required)
    def get(self,request):
        args={}
        address= UserAddress.objects.filter(user=request.user.Customer).first()        
        orders = Order.objects.filter(user=request.user)
        userform = EditUserForm(instance=request.user) 
        passwordform = ChangeUserPasswordForm(self.request.user)
        args['address'] = address        
        args['orders'] = orders
        args['userform'] = userform         
        args['passwordform'] = passwordform         
        return render(request,'customer/profile.html',args)
    
    @transaction.atomic
    @method_decorator(login_required)
    @method_decorator(sensitive_post_parameters())
    def post(self,request):
        args={}
        userform=EditUserForm(request.POST,instance=request.user)        
        passwordform=ChangeUserPasswordForm(self.request.user,request.POST)
        args['userform'] = userform                   
        if userform.is_valid():
            userform.save()                   
            messages.success(request,"Details changed successfully!")        
            return redirect("/customer/profile")                 
        return render(request,"customer/profile.html",args)

class ProfileDetails(View):
    @method_decorator(login_required)
    def get(self,request):
        args={}
        userform = EditUserForm(instance=request.user)        
        args['userform'] = userform        
        return render(request,"customer/profiledetails.html",args)

    @transaction.atomic
    @method_decorator(login_required)
    def post(self,request):
        args={}
        userform=EditUserForm(request.POST,instance=request.user)        
        args['userform'] = userform                                                
        messages.success(request,"Profile Details saved successfully!")
        if userform.is_valid(): 
            userform.save()       
            if len(UserAddress.objects.filter(user=request.user.Customer)) == 0:
                messages.info(request,"Please fill in your address details!")
                return redirect("/customer/address")     
            messages.success(request,"Profile Details saved successfully!")            
        return render(request,"customer/profiledetails.html",args) 

class ChangePassword(View):

    @method_decorator(login_required)
    @method_decorator(csrf_protect)    
    def get(self,request):
        form = ChangeUserPasswordForm(self.request.user)
        return render(request,"customer/changepassword.html",{"form":form})

    @method_decorator(sensitive_post_parameters())
    def post(self,request):
        form=ChangeUserPasswordForm(self.request.user,request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Password changed successfully! Please login again.")
            logout(request)
            return redirect("login")
        return render(request,"customer/changepassword.html",{"form":form})


def AllAddress(request):
    addresses = UserAddress.objects.filter(user=request.user.Customer, is_active=True)
    return render(request,"customer/myaddresses.html",{"addresses":addresses})

class Address(View):
    def get(self,request,id=0):              
        if id==0:            
            form = AddressForm()            
        else:
            try:
                address = UserAddress.objects.get(id=id,user=request.user.Customer)
                form = AddressForm(instance=address)
            except:
                pass        
        return render(request,"customer/address.html",{"form":form})  
    
    @transaction.atomic
    def post(self,request,id=0):        
        if id==0:
            form = AddressForm(request.POST)
        else:
            try:
                address = UserAddress.objects.get(id=id,user=request.user.Customer)
                form = AddressForm(request.POST,instance=address)
            except:
                pass
            
        if form.is_valid():
            cform = form.save(commit=False)
            cform.user = request.user.Customer
            cform.save()            
            messages.success(request,"Address details saved successfuly!")
            return redirect("profile")        
        return render(request,"customer/address.html",{"form":form}) 


# def DeleteAddress(request,id):
#     try:
#         address = UserAddress.objects.get(id=id,user=request.user.Customer)
#         address.is_active = False
#         address.save()
#     except:
#         return redirect("myaddresses")     
#     messages.success(request,"Address deleted successfully!")
#     return redirect("myaddresses")     

# def SetAddressAsDefault(request,id):    
#     addresses = UserAddress.objects.filter(user=request.user.Customer)
#     for address in addresses:
#         if address.id==id:
#             address.is_primary = True
#         else:
#             address.is_primary = False
#         address.save()
#     return redirect("myaddresses")     
    
    

templates/customer/activateaccount.html
{% extends 'design.html' %}
{% load static %}
{% load imagekit %}
{% load csswidgets %}
{% block title1 %}Sign Up{% endblock %}
{% block title2 %}Sign Up{% endblock %}

{% block content %}




<div class="ltn__login-area pb-110">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title-area text-center">
                    <h1 class="section-title">Activate <br>Your Account</h1>
                    
                    <h4><p></p>Please enter the OTP we have sent to your registered Email!</p></h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="account-login-inner">
                    <form action="" method="POST" class="ltn__form-box contact-form-box">
                        {% csrf_token %}                       
                        {{form.otp|attr:"placeholder:Add 6 digit OTP number here"}} 
                        <input name="uname" value="{{ request.session.uname }}">
                        <span class="text-danger d-block mt-2">{{form.username.errors|striptags}}</span>                        
                            <button class="theme-btn-1 btn reverse-color btn-block" type="submit">SUBMIT</button>
                        </div>
                    </form>                    
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}
<p>Register to get access to vast collection of all your garden needs</p>

templates/customer/orderplaced.html
{% extends 'design.html' %}
{% load customwidgets %}
{% block content %}

<div class="bg-lgreen p-4 shdw1 fs-3">Order Placed Successfully!</div>

<div class="bg-lgreen p-4 shdw1 mt-2">
    <h4>{{order.orderId}}</h4>
    {{order.orderStatus}}
    {{order.orderedOn}}
    {% for item in order.orderitems_set.all %}
    <div class="m-2 text-center text-lg-start">
        <span class="fw-bold mb-2 d-inline-block"><a href="{% url 'details' item.id %}" style="color:black;">{{item.productName}}</a></span><br>
        <span class="fw-bold me-5">Price: Rs. {{item.paidPrice|floatformat:2}}</span>
        <span class="fw-bold me-5">Tax:  Rs. {{item.taxamt|floatformat:2}}</span>
        <span class="fw-bold me-5">Discount:  Rs. {{item.discountamt|floatformat:2}}</span>
        <span class="fw-bold">{{item.quantity}} Unit(s)</span>
        <span>
        {% if order.orderStatus == "delivered" and order.deliveryDate|returnvalid and item.returnRequested == False %}            
        <form action="{% url 'returnproduct' item.id %}" method="POST" class="d-inline">
            {% csrf_token %}
            <button class="btn btn-outline-danger btn-sm p-1 ms-2">Return</button>
            <button type="submit" class="theme-btn-1 btn btn-effect-1">Save Address</button>
        </form>
        {% elif item.returnRequested %}
        <span class="text-danger ms-2 fw-bold">{{item.returnStatus}}</span>
        {% endif %}
        </span>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/customer/orders.html
{% extends 'design.html' %}
{% load csswidgets%}
{% load customwidgets %}

{% block content %}
{% if orders.count == 0 %}
<div class="text-center m-auto bg-lgreen mt-5 p-4 shdw1 fw-bold fs-3">No Orders Yet!</div>
{% endif %}
{% for order in orders %}
<div class="shdw1 bg-lgreen m-4 p-3 rounded">
    <div class="float-lg-start">
        <h6 class="fs-small fw-bold">{{order.orderedOn|date:"l, d F Y"}}</h6>
        <h3>{{order.orderId}}</h3>    
        <h6 class="">Total Paid: Rs. {{order.orderTotal|floatformat:2}}</h6>
        <h6 class="">Order Status: {{order.orderStatus}}</h6>

    </div>
    <div class="float-lg-end text-center border rounded">        
        {% if order.trackingProvider != "" %}
        <b class="p-2 text-light bg-secondary d-block rounded-top">Tracking Info</b>
            <div class="p-2 bg-light">
                <h6>Courier Partner: {{order.trackingProvider}}, 
                AWB number: {{order.trackingInfo}}</h6>
            </div>
        {% endif %}        
        
        
        
        
    </div>
    <div class="clearfix"></div>
    <hr/>

    {% for item in order.orderitems_set.all %}
    
        <div class="m-2 text-center text-lg-start">
            <span class="fw-bold mb-2 d-inline-block"><a href="{% url 'details' item.productId %}" style="color:black;">{{item.productName}}</a></span><br>
            <span class="fw-bold me-5">Price: Rs. {{item.paidPrice|floatformat:2}}</span>
            <span class="fw-bold me-5">Tax:  Rs. {{item.taxAmount|floatformat:2}}</span>
            <span class="fw-bold me-5">Discount:  Rs. {{item.discountAmount|floatformat:2}}</span>
            <span class="fw-bold">{{item.quantity}} Unit(s)</span>
            <span>
            {% if order.orderStatus == "delivered" and order.deliveryDate|returnvalid and item.returnRequested == False %}            
            <form action="{% url 'returnproduct' item.id %}" method="POST" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-outline-danger btn-sm p-1 ms-2">Return</button>
            </form>
            {% elif item.returnRequested %}
            <span class="text-danger ms-2 fw-bold">{{item.returnStatus}}</span>
            {% endif %}
            </span>
        </div>

        <hr class="me-5"/>
            
    
    
    {% endfor %}
    
<a class="btn btn-outline-success ms-2" href="{% url 'getinvoice' order.id%}">Print Invoice</a>
        {% if order.orderStatus == "Processing" or order.orderStatus == "packed" %}
        <form action="{% url 'cancelorder' order.id %}" method="POST" class="d-inline">
            {% csrf_token %}
            <button class="btn btn-outline-danger ms-2">Cancel Order</button>
        </form>        
        {% endif %}

</div>
{% endfor %}


{% endblock content %}

templates/customer/printinvoice.html
{% load static %}
{% load mathfilters %}
{% load customwidgets %}
<link rel="stylesheet" href="{% static 'css/tp/bootstrap.css' %}" />    
<link rel="stylesheet" href="{% static 'css/design.css' %}" />
<body style="background-color:#FFFFFF;">


<div class="m-auto mb-4">



<div class="container mt-2 p-2 " style="min-height:1000px;">
<div class="m-4 mb-4 float-start h1 fw-bold"><h1>GAGAN PUNIA GROUP</h1></div>
<div class="m-4 mb-4 float-end"><img src="{% static "assets/logo1.png" %}" width=150px height="105px" alt=""></div>
<div class="clearfix"></div>
<div class= "m-4 m-auto text-center"><h3 class="">TAX INVOICE</h3></div>

<div class=" ms-4 p-2 mb-4 float-start rounded">
<h6 class=" m-2 mb-2 "><b>Order Id:</b> {{order.orderId}}</h6>
<h6 class=" m-2 mb-2 "><b>Order Date:</b> {{order.orderedOn}}</h6>
<h6 class=" m-2 mb-2 "><b>Order Total:</b> ₹ {{order.orderTotal|floatformat:2}}</h6>
<h6 class=" m-2 mb-2 "><b>GST Deducted:</b> ₹ {{order.taxOnOrder|floatformat:2}} </h6>
<h6 class=" m-2 mb-2 "><b>Coupon Code (if any):</b> {{order.couponCode}} </h6>
<h6 class=" m-2 mb-2 "><b>Discount (if any):</b> ₹ {{order.discount|floatformat:2}} </h6>
<br/>
<h6 class="m-2 mb-2 text-black fw-bold">Invoice Number : {{invoice.invoiceNo}}</h6>
<h6 class="m-2 mb-2 text-black fw-bold">Invoice Date : {{invoice.invoiceDate}}</h6>
<br/>
<h6 class="text-black fw-bold  m-2 mb-2">Sold by:</h6>
{% for vendor in vendors  %}
<h6 class=" m-2 mb-2 ">{{vendor.user.fullName}}</h6>
<h6 class=" m-2 mb-2 ">{{vendor.address.address1}}, {{vendor.address.address2}}</h6>
<h6 class=" m-2 mb-2 "> {{vendor.address.state|hyphenurl}} - {{vendor.address.pinCode}}</h6>
<h6 class=" m-2 mb-2"><b>PAN Number: </b>{{vendor.panNumber}} </h6>
<h6 class=" m-2 mb-2"><b>GST: </b>{{vendor.gstNumber}} </h6>

{% endfor %}

</div>
<div class=" p-2 me-4 float-end ms-4 rounded">
<h6 class="text-black fw-bold m-2 mb-2">Shipping Address:</h6>
<h6 class=" m-2 mb-2 fw-bold ">{{address.contactPerson}} </h6>
<h6 class=" m-2 mb-2">{{order.user.username}} </h6>
<h6 class=" m-2 mb-2">{{address.address1}},{{address.address2}} </h6>
<h6 class=" m-2 mb-2"> {{address.state|hyphenurl}} - {{address.pinCode}}</h6>
<h6 class=" m-2 mb-2">{{address.contactNumber}} </h6>

</div>


<div class="clearfix"></div>
<h6 class=" text-black fw-bold m-2">Purchase Details:</h6>
<div class="table-responsive">
<table class="table table-borderless text-center">
<thead class="bg-secondary text-light">
<th class="rounded-start">#</th>
<th>Item</th>
<th>Quantity</th>
<th>List Price</th>
<th>Discount</th>
<th>GST</th>
<th class="rounded-end">Total Price</th>
</thead>
<tbody>
{% for orderitem in order.orderitems_set.all %}
<tr>
<td class="">{{forloop.counter}}</td>
<td class="">{{orderitem.productName}}UltraBreed<sup>TM</sup></td>
<td class="">{{orderitem.quantity}}</td>
<td class="">₹ {{orderitem.listPrice|mul:orderitem.quantity|floatformat:2}}</td>
<td class="">₹ {{orderitem.discountAmount|floatformat:2}}</td>
<td class="">₹ {{orderitem.taxAmount|floatformat:2}}</td>
<td class="">₹ {{orderitem.paidPrice|floatformat:2}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
<hr/>
<p class=" fs-xsmall text-end m-2">This invoice is generated digitally and hence does not require any signatures.</p>
<p class=" fs-xsmall text-end m-2">Paperless billing</p>

</div>
</div>

</body>