customer/urls.py
from django.urls import path
from . import views


urlpatterns = [    
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('resendactivationemail/',views.ResendActivationEmail.as_view(),name='resendactivationemail'),   

    # path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('activate/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('resetpassword/',views.ResetPassword.as_view(),name='resetpassword'),
    path('createnewpassword/<uidb64>/<token>/',views.CreateNewPassword.as_view(),name="createnewpassword"),  

    path('profile/',views.Profile.as_view(),name='profile'),
    # path('profiledetails/',views.ProfileDetails.as_view(),name='profiledetails'),
    path('changepassword/',views.ChangePassword.as_view(),name='changepassword'),
    #path('myaddresses/',views.AllAddress,name='myaddresses'),
    path('address/',views.Address.as_view(),name='address'),
    path('address/<int:id>',views.Address.as_view(),name='address'),
    #path('deleteaddress/<int:id>',views.DeleteAddress,name='deleteaddress'),
    #path('setasdefault/<int:id>',views.SetAddressAsDefault,name='setasdefault'),

    path('ordersuccess/',views.OrderPlaced,name='ordersuccess'),
    path('orderfailed/',views.OrderFailed,name='orderfailed'),
    path('ordersuccessful/<str:orderid>',views.OrderSuccess,name='ordersuccessful'),
    path('printinvoice/<str:orderid>/',views.PrintInvoice,name='printinvoice'),
    path('getinvoice/<str:orderid>/',views.GetInvoice,name='getinvoice'),

    path('orders/',views.Orders,name='orders'),
    # path('tracking/<int:oid>/',views.UpdateTrackingInfo,name='tracking'),
    # path('updatestatus/<int:oid>/',views.UpdateOrderStatus,name='updatestatus'),

    path('cancelorder/<int:oid>/',views.CancelOrder,name='cancelorder'),
    path('returnproduct/<int:orderitemid>/',views.ReturnProduct,name='returnproduct'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('',views.index,name='home'),  
    path('cartsummary/',views.cartsummary,name='cartsummary'),
    path('makepayment/',views.MakePayment,name='makepayment'),
    path('category/<str:cid>/',views.FilterByCategory,name='category'),
    path('allproducts/',views.AllProducts,name='allproducts'),
    path('search/',views.SearchResults,name='search'),

    path('filterproduct',views.FilterProducts,name='filterproduct'),
    path('clearfilter/',views.ClearFilter,name='clearfilter'),
    path('clearfilter/<str:category>/',views.ClearFilter,name='clearfilter'),
    path('pinproducts/',views.FilterByPin,name="pinproducts"), 

    path('aboutus/',views.AboutUs,name='aboutus'),
    path('affiliate/',views.Affiliate,name='affiliate'),
    path('cancellations/',views.Cancellations,name='cancellations'),
    path('careers/',views.Careers,name='careers'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('faqs/',views.FAQ,name='faqs'),
    path('help/',views.Help,name='help'),
    path('payments/',views.Payments,name='payments'),
    path('payouts/',views.Payouts,name='payouts'),
    path('press/',views.Press,name='press'),
    path('howtocare/', views.Howtocare,name='howtocare'),
    path('privacypolicy/',views.PrivacyPolicy,name='privacypolicy'),
    path('refundpolicy/',views.RefundPolicy,name='refundpolicy'),
    path('returnpolicy/',views.ReturnPolicy,name='returnpolicy'),
    path('shippingpolicy/',views.ShippingPolicy,name='shippingpolicy'),
    path('terms/',views.TermsAndConditions,name='terms'),
    path('vendorfaqs/',views.VendorFAQ,name='vendorfaqs'),
    path('vendorassistance/',views.VendorHelp,name='vendorassistance'),
    path('requestproduct/',views.RequestProduct,name='requestproduct'),   
    #path('404/',views.PageNotFound,name='404'),
    #path('404/',views.ServerUnavailable,name='503'),
    path("test-session/", views.test_session)

    
]

podhewale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path(settings.SECRET_ADMIN_URL +'/admin/', admin.site.urls),
	    path('',include('home.urls')),
	    path('customer/',include('customer.urls')),
	    path('vendor/',include('vendor.urls',namespace="vendor")),
	    path('product/',include('product.urls')),
	] 

if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxLengthValidator, MinLengthValidator

# ENUMS


GENDER = (("Male", "Male"), ("Female", "Female"), ("Other", "Other"))

class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    fullName = models.CharField(max_length=100,null=True,blank=True)
    gender = models.CharField(max_length=10,choices=GENDER,null=True,blank=True)    
    contactNumber = models.CharField(max_length=10,validators=[MinLengthValidator(10),MaxLengthValidator(10)],blank=True,null=True) 

class Invoice(models.Model):
    def CustomInvoiceId(self):
        return "INV" + str(self.id)
    order = models.CharField(max_length=20,blank=True,null=True)
    invoiceNo = property(CustomInvoiceId)
    invoiceDate=models.DateTimeField(auto_now_add = True)

templates/common/activateaccount.html
{% autoescape off %}

<body style="background-color:#FFFFFF;font-family:Arial;">
<div style="border:1px solid #999;border-radius:3px;margin:auto;padding:50px;max-width:600px;">

<p style="margin-top:10px;">Dear {{ mailto }},</p>

<p style="margin-top:25px;">Thank you for registering on {{website|lower}}</p>

<p style="margin-top:25px;">We aim to provide ease of access and door step delivery of all your gardening needs.</p>

{% comment %} <p style="margin-top:25px;"><a style="padding:10px; border-radius:3px;background-color:rgb(100,100,255);color:#FFF;text-decoration:none;font-weight:bold" href="http://{{ domain }}{% url 'activateaccount' uidb64=uid token=token %}">Activate My Account</a></p> {% endcomment %}

{% comment %} <p style="margin-top:25px;">If the link above is not working for you, kindly copy and paste the code below in your brower to activate your account:-</p> {% endcomment %}
<p style="margin-top:25px;">Here is your OTP to activate your account with us</p></br>
<b>{{otp}}</b>

{% comment %} http://{{ domain }}{% url 'activateaccount' uidb64=uid token=token %} {% endcomment %}

<p style="margin-top:25px;">With best regards,<br/>
{{repname }} 
</p>


</div>
</body>

{% endautoescape %}

templates/common/activatevendoraccount.html
{% autoescape off %}

<body style="background-color:#FFFFFF;font-family:Arial;">
<div style="border:1px solid #999;border-radius:3px;margin:auto;padding:50px;max-width:600px;">

<p style="margin-top:10px;">Dear {{ mailto }},</p>

<p style="margin-top:25px;">Thank you for registering on {{website|lower}}</p>

<p style="margin-top:25px;">We aim to provide ease of access and door step delivery of all your gardening needs.</p>

<p style="margin-top:25px;"><a style="padding:10px; border-radius:3px;background-color:rgb(100,100,255);color:#FFF;text-decoration:none;font-weight:bold" href="http://{{ domain }}{% url 'activateaccount' uidb64=uid token=token %}">Activate My Account</a></p>

<p style="margin-top:25px;">If the link above is not working for you, kindly copy and paste the code below in your brower to activate your account:-</p>

http://{{ domain }}{% url 'vendor:activateaccount' uidb64=uid token=token %}

<p style="margin-top:25px;">With best regards,<br/>
{{repname }} 
</p>


</div>
</body>

{% endautoescape %}

templates/common/resetaccountpassword.html
{% autoescape off %}

<body style="background-color:#FFFFFF;font-family:Arial;">
    <div style="border:1px solid #999;border-radius:3px;margin:auto;padding:50px;max-width:600px;">       

        <p style="margin-top:10px;">Dear {{ mailto }},</p>

        <p style="margin-top:25px;">To reset your account password, please click on the link provided below.</p>

        <p style="margin-top:25px;"><a
                style="padding:10px; border-radius:3px;background-color:rgb(100,100,255);color:#FFF;text-decoration:none;font-weight:bold"
                href="http://{{ domain }}{% url 'createnewpassword' uidb64=uid token=token %}">Reset your
                password</a></a></p>

        <p style="margin-top:25px;">If the link above is not working for you, kindly copy and paste the code below in
            your brower to reset your account password:-</p>

        http://{{ domain }}{% url 'createnewpassword' uidb64=uid token=token %}

        <p style="margin-top:25px;">Hoping to see you soon once again on {{website}}.</p>

        <p style="margin-top:25px;">With best regards,<br />{{repname }}</p>

    </div>



    {% endautoescape %}

templates/common/resetaccountpassword_v.html
{% autoescape off %}

<body style="background-color:#FFFFFF;font-family:Arial;">
    <div style="border:1px solid #999;border-radius:3px;margin:auto;padding:50px;max-width:600px;">       

        <p style="margin-top:10px;">Dear {{ mailto }},</p>

        <p style="margin-top:25px;">To reset your account password, please click on the link provided below.</p>

        <p style="margin-top:25px;"><a
                style="padding:10px; border-radius:3px;background-color:rgb(100,100,255);color:#FFF;text-decoration:none;font-weight:bold"
                href="http://{{ domain }}{% url 'vendor:createnewpassword' uidb64=uid token=token %}">Reset your
                password</a></a></p>

        <p style="margin-top:25px;">If the link above is not working for you, kindly copy and paste the code below in
            your brower to reset your account password:-</p>

        http://{{ domain }}{% url 'vendor:createnewpassword' uidb64=uid token=token %}

        <p style="margin-top:25px;">Hoping to see you soon once again on {{website}}.</p>

        <p style="margin-top:25px;">With best regards,<br />{{repname }}</p>

    </div>



    {% endautoescape %}