customer/urls.py
from django.urls import path
from . import views


urlpatterns = [    
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout,name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('resendactivationemail/',views.ResendActivationEmail.as_view(),name='resendactivationemail'),   

    # path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('activate/',views.ActivateAccount.as_view(),name="activateaccount"),
    path('resetpassword/',views.ResetPassword.as_view(),name='resetpassword'),
    path('createnewpassword/<uidb64>/<token>/',views.CreateNewPassword.as_view(),name="createnewpassword"),  

    path('profile/',views.Profile.as_view(),name='profile'),
    # path('profiledetails/',views.ProfileDetails.as_view(),name='profiledetails'),
    path('changepassword/',views.ChangePassword.as_view(),name='changepassword'),
    #path('myaddresses/',views.AllAddress,name='myaddresses'),
    path('address/',views.Address.as_view(),name='address'),
    path('address/<int:id>',views.Address.as_view(),name='address'),
    #path('deleteaddress/<int:id>',views.DeleteAddress,name='deleteaddress'),
    #path('setasdefault/<int:id>',views.SetAddressAsDefault,name='setasdefault'),

    path('ordersuccess/',views.OrderPlaced,name='ordersuccess'),
    path('orderfailed/',views.OrderFailed,name='orderfailed'),
    path('ordersuccessful/<str:orderid>',views.OrderSuccess,name='ordersuccessful'),
    path('printinvoice/<str:orderid>/',views.PrintInvoice,name='printinvoice'),
    path('getinvoice/<str:orderid>/',views.GetInvoice,name='getinvoice'),

    path('orders/',views.Orders,name='orders'),
    # path('tracking/<int:oid>/',views.UpdateTrackingInfo,name='tracking'),
    # path('updatestatus/<int:oid>/',views.UpdateOrderStatus,name='updatestatus'),

    path('cancelorder/<int:oid>/',views.CancelOrder,name='cancelorder'),
    path('returnproduct/<int:orderitemid>/',views.ReturnProduct,name='returnproduct'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('',views.index,name='home'),  
    path('cartsummary/',views.cartsummary,name='cartsummary'),
    path('makepayment/',views.MakePayment,name='makepayment'),
    path('category/<str:cid>/',views.FilterByCategory,name='category'),
    path('allproducts/',views.AllProducts,name='allproducts'),
    path('search/',views.SearchResults,name='search'),

    path('filterproduct',views.FilterProducts,name='filterproduct'),
    path('clearfilter/',views.ClearFilter,name='clearfilter'),
    path('clearfilter/<str:category>/',views.ClearFilter,name='clearfilter'),
    path('pinproducts/',views.FilterByPin,name="pinproducts"), 

    path('aboutus/',views.AboutUs,name='aboutus'),
    path('affiliate/',views.Affiliate,name='affiliate'),
    path('cancellations/',views.Cancellations,name='cancellations'),
    path('careers/',views.Careers,name='careers'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('faqs/',views.FAQ,name='faqs'),
    path('help/',views.Help,name='help'),
    path('payments/',views.Payments,name='payments'),
    path('payouts/',views.Payouts,name='payouts'),
    path('press/',views.Press,name='press'),
    path('howtocare/', views.Howtocare,name='howtocare'),
    path('privacypolicy/',views.PrivacyPolicy,name='privacypolicy'),
    path('refundpolicy/',views.RefundPolicy,name='refundpolicy'),
    path('returnpolicy/',views.ReturnPolicy,name='returnpolicy'),
    path('shippingpolicy/',views.ShippingPolicy,name='shippingpolicy'),
    path('terms/',views.TermsAndConditions,name='terms'),
    path('vendorfaqs/',views.VendorFAQ,name='vendorfaqs'),
    path('vendorassistance/',views.VendorHelp,name='vendorassistance'),
    path('requestproduct/',views.RequestProduct,name='requestproduct'),   
    #path('404/',views.PageNotFound,name='404'),
    #path('404/',views.ServerUnavailable,name='503'),
    path("test-session/", views.test_session)

    
]

podhewale/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path(settings.SECRET_ADMIN_URL +'/admin/', admin.site.urls),
	    path('',include('home.urls')),
	    path('customer/',include('customer.urls')),
	    path('vendor/',include('vendor.urls',namespace="vendor")),
	    path('product/',include('product.urls')),
	] 

if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/503.html
{% extends 'design.html' %}
{% block content %}
<div class="d-flex justify-content-center align-content-cente bg-lgreen p-3 rounded" style="min-height:50vh;">
    <div class="align-self-center h6 fw-bold text-center">
        <h1>SORRY!</h1> Looks like our server is unavailable at the moment. Can you please try us after some time?
    </div>
</div>
{% endblock content %}

templates/aboutus.html
{% extends 'design.html' %}
{% block content %}
<div>About
Your own Podhewale.com is a horticulture e-commerce platform which enables you to nurture the Nature within the available resources. The website includes the offers and products related to the Plants which can be useful for anyone to get connected with the Nature and we will make our best to provide you the required resources for the same.</div>

{% endblock content %}

templates/design2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title> PodheWale |
    {% block title %}{% endblock title %}
  </title>
  {% block meta %}{% endblock meta%}
  {% comment %} CSS FILES{% endcomment %}
  <link rel="stylesheet" href="{% static 'css/tp/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/selectize.bootstrap5.css' %}">
  {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" /> {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css" integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  
  <link rel="stylesheet" href="{% static 'css/design.css' %}" />
  <link rel="stylesheet" href="{% static 'css/custombs.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/xzoom.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/magnific-popup.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/bxslider.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/aos.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tp/wow.css' %}" />

  {% comment %} CSS FILES END {% endcomment %}

  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon.png' %}">

  {% comment %} <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script> {% endcomment %}

</head>

<body>
  <div class="overlay" style="display:block" hidden="hidden"></div>

  {% comment %} <div class="see"><a href="#">show overlay</a></div> {% endcomment %}

  

  {% comment %} <div style="display:none;" id="myDiv" class="animate-bottom container-fluid"> {% endcomment %}
    {% comment %} <div id="loader"></div> {% endcomment %}
    <div id="" class="animate-bottom container-fluid m-0 p-0">
    

    {% include "headsection.html" %}
    {% comment %} {% include "mainsection.html" %} {% endcomment %}
    <div class="container-fluid p-1" style="min-height:600px;">
      {% block content %}{% endblock content %}
    </div>
    {% include "footer.html" %}
  </div>
  
  <a href="https://wa.me/919911554948?text=Welcom%20To%20PodheWale!"><i class="fa-brands fa-whatsapp-square whatsapp" data-bs-toggle="tooltip" data-bs-placement="left" title="Connect through Whatsapp"></i></a>
  <a href="{% url 'requestproduct' %}" class="ondemand text-center"><i class="fas fa-envelope-open" data-bs-toggle="tooltip" data-bs-placement="left" title="Request for a custom Product"></i></a>
  <a href="#" class="uparrow text-center"><i class="fas fa-arrow-alt-circle-up" data-bs-toggle="tooltip" data-bs-placement="left" title="Go to Top"></i></a>
  
 

  {% comment %} JS FILES{% endcomment %}
  <script type="text/javascript" src="{% static 'js/tp/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/bxslider.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/popper.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/bootstrap.min.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script type="text/javascript" src="{% static 'js/tp/selectize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/hammer.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/tp/magnific-popup.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/tp/xzoom.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/setup.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/rating.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/aos.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/wowslider.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/tp/script.js' %}"></script>



  {% comment %} JS FILES END{% endcomment %}
  {% block scripts %}{% endblock scripts %}

  {% if messages %}
  <script>
    {% for message in messages %} 
    {%if message.tags == 'error' %}
    swal("An error occured!", '{{message}}', "error") 
    {% elif message.tags == 'success' %}
    swal("Success!", '{{message}}', "success") 
    {% elif message.tags == 'info' %}
    swal("Please note!", '{{message}}', "info") 
    {% elif message.tags == 'warning' %}
    swal("Alert!", '{{message}}', "warning") 
    {% endif %} 
    {% endfor %}
  </script>
  {% endif %}

  {% if form.non_field_errors %}
  <script>
    var err=""
    {% for error in form.non_field_errors %}
    err = err + '{{error}}' + "\n" 
    {% endfor %}
    console.log(err)
    swal("An error occured!", err, "error")
  </script>
  {% endif %}


  {% comment %} <script>
    $(function () {
      $("a").click(function () {
        $(".overlay").attr("hidden", "hidden")

      });
    });
  </script> {% endcomment %}
  {% comment %} <script>
    $(function () {
      if ($("#pinbox").val() != 'All') {
        $(".overlay").attr("hidden", "hidden")
      } else {
        $(".overlay").removeAttr("hidden")
      }
    })
  </script> {% endcomment %}

  <script>
    $(document).ready(function () {
      $('.slider2').bxSlider({
        auto: true,
        mode: 'vertical',
        autoHover: true,
        pager: false
      });
      $('.slider').bxSlider({
        auto: true,
        mode: 'horizontal',
        autoHover: true,
        pager: false
      });
      $('.slider3').bxSlider({
        auto: true,
        mode: 'horizontal',
        autoHover: true,
        pager: false
      });
    });
  </script>
  <script>
    $(document).ready(function () {

      AOS.init();



    });
  </script>

  {% comment %} <script>
    var cvalue = 0
    $(document).mouseleave(function () {
      if (cvalue == 0) {
        swal("Please don't leave just yet!",
          'Get a discount of 15% on your first order! \n\n Use Coupon code PODHE15', "info")
        cvalue = 1
      }

    });
  </script>  {% endcomment %}

  <script>

  

    $(function(){
      $("#loader").attr("style","display:none;")
      $("#myDiv").attr("style","display:block;")      
    })    

  </script>

 <script>
    anm = function loopme()
    {
      $(".whatsapp").animate(
        {
          opacity:0.25,
        },
        1000, function()
        {
          $(".whatsapp").animate({
              opacity:1,
            },1000, anm()
          )
        }
      )
    }
    anm();
  </script>

  <script>
    anm2 = function loopme()
    {
      $(".ondemand").animate(
        {
          opacity:0.25,
        },
        1000, function()
        {
          $(".ondemand").animate({
              opacity:1,
            },1000, anm2()
          )
        }
      )
    }
    anm2();
  </script>

  <script>
    anm3 = function loopme()
    {
      $(".uparrow").animate(
        {
          opacity:0.25,
        },
        1000, function()
        {
          $(".uparrow").animate({
              opacity:1,
            },1000, anm3()
          )
        }
      )
    }
    anm3();
  </script> 

  <script>
    $(".uparrow").click(function () {
        $('html, body').animate({
            scrollTop: 0
        }, 'fast');
    })
</script>
<script>
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl)
  })
  </script>

  <script>
    $(".whatsapp").hover(function() {
      $('.whatsapp').stop(true).fadeTo(200, 1);
    }, function() {
      $('.whatsapp').stop(true).fadeTo(200, 1);
    });
  </script>

  <script>
    $(".ondemand").hover(function() {
      $('.ondemand').stop(true).fadeTo(200, 1);
    }, function() {
      $('.ondemand').stop(true).fadeTo(200, 1);
    });
  </script>

<script>
  $(".uparrow").hover(function() {
    $('.uparrow').stop(true).fadeTo(200, 1);
  }, function() {
    $('.uparrow').stop(true).fadeTo(200, 1);
  });
</script>



</body>

</html>

templates/headsection copy.html
{% load static %}
{% load customwidgets %}

<div class="container-fluid p-0">
  {% comment %} <div class="container">

    <div class="row text-lg-start pb-2">

      <div class="col-12 col-lg-2">
        <a href="{% url 'home' %}" class="text-decoration-none text-black">
          <img class="img-fluid  mt-1" src="{% static 'assets/logo.png' %}" width="140px" alt="">

        </a>
      </div>

      <div class="col-12 col-lg">
        <form action="{% url 'search' %}" class="searchgroup" style="z-index:1;">
          <div class="input-group">
            <input type="text" class="form-control searchbox" name="search">
            <button type="submit" class="btn bg-green"><i class="fa fa-search"></i></button>
          </div>
        </form>
      </div>

      <div class="col-12 col-lg searchgroup">

        <div class="float-start mt-0 see" style="top:-3px;">

          <form action="{% url 'pinproducts' %}" method="GET" class="" style="top:-20px; display:block;">
            <div class="input-group">
              <span class="form-control border-0  me-1 fw-bold" style="padding-top:7px;">Pincode:</span>
              {% if request|pinvalue == False %}
              <input type="text" name="filterpincode" id="pinbox" readonly class="form-control-plaintext" value="All"
                style="width:20px;">
              {% else %}
              <input type="text" name="filterpincode" id="pinbox" readonly class="form-control-plaintext rounded"
                value="{{request|pinvalue}}" style="width:55px;">
              {% endif %}
              <a class="btn-link btn mt-0 ms-0 ps-1 pe-0 text-decoration-none" id="pinbtn"
                onclick="showform()">Change</a>
              <button type="submit" id="pinsubmit" class="btn bg-green text-dark mt-0 me-0 text-decoration-none"
                hidden="hidden">Change</button>

            </div>
          </form>

        </div>




        {% if user.is_anonymous %}
        <div class="float-start shdw2 me-2 bo">
          <a href="{% url 'login' %}" class="btn bg-green fw-bold" style="padding:3px 5px;">Login</a>
        </div>
        <div class="float-start shdw2 me-2">
          <a href="{% url 'signup' %}" class="btn bg-green fw-bold" style="padding:3px 5px;">Signup</a>
        </div>
        {% elif user.is_customer %}

        <div class="dropdown float-start shdw2 me-2">
          <a class="btn bg-secondary text-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item fs-small" href="{% url 'profile' %}">Profile</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'myaddresses' %}">Addresses</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'wishlist' %}">Wishlist</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'orders' %}">Orders</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'changepassword' %}">Change Password</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'logout' %}">Sign Out</a></li>
          </ul>
        </div>
        {% elif user.is_vendor %}
        <div class="dropdown float-start shdw2 me-2">
          <a class="btn bg-secondary text-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:dashboard' %}">Dashboard</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'products' %}">Manage Products</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:orders' %}">Manage Orders</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:profile' %}">Profile</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:address' %}">Address</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:bankdetails' %}">Bank Details</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:changepassword' %}">Change Password</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:logout' %}">Sign Out</a></li>
          </ul>
        </div>


        {% endif %}
        {% if user.is_anonymous or user.is_customer %}
        <a href="{% url 'cartsummary' %}" class="btn bg-green position-relative shdw2" style="padding:3px 5px;">
          <i class="fas fa-shopping-cart"></i>
          
          <span
            class="p-1 bg-light rounded-3 flost fw-bold ms-1 text-success">{{request.session.cart.keys|length}}</span>
        </a>
        {% endif %}

      </div>

    </div>



    
  </div>
  <div class="container-fluid p-0">

    <div class="row m-auto px-5 categories text-center container p-0">

      {% for category in categories  %}
      <div class="col-2">
        <a href="{% url 'category' category.categoryName %}">
          <div class="py-2 text-center rounded">
            <img src="{{category.categoryImage.url}}" alt="Flower Vase" class="img-fluid">
            <span class="d-block  pt-2 fw-bold">{{category.categoryName}}</span>
          </div>
        </a>
      </div>
      {% endfor %}

    </div>


  </div> {% endcomment %}



</div>


<nav class="navbar navbar-expand-lg container">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img class="img-fluid  mt-1" src="{% static 'assets/logo.png' %}" width="140px" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="border-0"><i class="fas fa-bars"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="col-12 col-lg">
        <form action="{% url 'search' %}" class="searchgroup" style="z-index:1;">
          <div class="input-group">
            <input type="text" class="form-control searchbox" name="search">
            <button type="submit" class="btn bg-green"><i class="fa fa-search"></i></button>
          </div>
        </form>
      </div>

      <div class="col-12 col-lg searchgroup">

        <div class="float-start mt-0 see" style="top:-3px;">

          <form action="{% url 'pinproducts' %}" method="GET" class="" style="top:-20px; display:block;">
            <div class="input-group">
              <span class="form-control border-0  me-1 fw-bold" style="padding-top:7px;">Pincode:</span>
              {% if request|pinvalue == False %}
              <input type="text" name="filterpincode" id="pinbox" readonly class="form-control-plaintext" value="All"
                style="width:20px;">
              {% else %}
              <input type="text" name="filterpincode" id="pinbox" readonly class="form-control-plaintext rounded"
                value="{{request|pinvalue}}" style="width:55px;">
              {% endif %}
              <a class="btn-link btn mt-0 ms-0 ps-1 pe-0 text-decoration-none" id="pinbtn"
                onclick="showform()">Change</a>
              <button type="submit" id="pinsubmit" class="btn bg-green text-dark mt-0 me-0 text-decoration-none"
                hidden="hidden">Change</button>

            </div>
          </form>

        </div>




        {% if user.is_anonymous %}
        <div class="float-start me-5">
          <a href="{% url 'login' %}" class="text-decoration-none text-black">
            <i class="fas fa-user cicon bg-green"></i>
            <span class="d-block">Login</span>
          </a>
        </div>
        <div class="float-start me-5">
          <a href="{% url 'signup' %}" class="text-decoration-none text-black">
            <i class="fas fa-user cicon bg-green"></i>
            <span class="d-block">SignUp</span>
          </a>
        </div>
        {% elif user.is_customer %}

        <div class="dropdown float-start shdw2 me-2">
          <a class="btn bg-secondary text-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item fs-small" href="{% url 'profile' %}">Profile</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'myaddresses' %}">Addresses</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'wishlist' %}">Wishlist</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'orders' %}">Orders</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'changepassword' %}">Change Password</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'logout' %}">Sign Out</a></li>
          </ul>
        </div>
        {% elif user.is_vendor %}
        <div class="dropdown float-start shdw2 me-2">
          <a class="btn bg-secondary text-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:dashboard' %}">Dashboard</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'products' %}">Manage Products</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:orders' %}">Manage Orders</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:profile' %}">Profile</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:address' %}">Address</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:bankdetails' %}">Bank Details</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:changepassword' %}">Change Password</a></li>
            <li><a class="dropdown-item fs-small" href="{% url 'vendor:logout' %}">Sign Out</a></li>
          </ul>
        </div>


        {% endif %}
        {% if user.is_anonymous or user.is_customer %}
        <div class="float-start me-3">
        <a href="{% url 'cartsummary' %}" class="text-decoration-none text-black">          
            <i class="fas fa-shopping-cart cicon bg-green"></i>
            <span class="d-block text-center">Cart</span>
            {% comment %} <span class="d-block">{{request.session.cart.keys|length}}</span> {% endcomment %}
        </a> 
      </div>
        {% endif %}

      </div>
      
    </div>
  </div>
  <br/>
    
</nav>
<div class="row m-auto px-5 categories text-center container p-0">

  {% for category in categories  %}
  <div class="col-2">
    <a href="{% url 'category' category.categoryName %}">
      <div class="py-2 text-center rounded">
        <img src="{{category.categoryImage.url}}" alt="Flower Vase" class="img-fluid">
        <span class="d-block  pt-2 fw-bold">{{category.categoryName}}</span>
      </div>
    </a>
  </div>
  {% endfor %}

</div>


{% block scripts %}
<script>
  function unhideform() {
    $("#addpinbox").attr("hidden", "hidden")
    $("#pinbox").removeAttr("hidden")
  }
</script>

<script>
  function showform() {

    $("#pinbox").removeAttr("readonly")
    $("#pinbox").removeClass("form-control-plaintext")
    $("#pinbox").addClass("form-control")
    $("#pinbox").removeAttr("style")
    $("#pinbox").val("")
    $("#pinbox").attr("style", "max-width:100px;")
    $("#pinbtn").attr("hidden", "hidden")
    $("#pinsubmit").removeAttr("hidden")
  }
</script>










{% endblock scripts %}

templates/headsection.html
{% load static %}

templates/mainsection.html
<div class="container-fluid bg-info maincontent">
    mainsection
    {% block content %}{% endblock content %}
</div>

templates/offers.html
{% load static %}
    <div class="slider">
        <div><img src="{% static 'assets/offers/Offer1.jpg' %}" class="img-fluid w-100" alt=""></div>
        <div><img src="{% static 'assets/offers/Offer2.jpg' %}" class="img-fluid w-100" alt=""></div>
        <div><img src="{% static 'assets/offers/Offer3.jpg' %}" class="img-fluid w-100" alt=""></div>
        <div><img src="{% static 'assets/offers/Offer4.jpg' %}" class="img-fluid w-100" alt=""></div>
        <div><img src="{% static 'assets/offers/Offer5.jpg' %}" class="img-fluid w-100" alt=""></div>        
    </div>